import { useCanvasStore } from '../store/canvasStore';
import type { CanvasObject, CanvasBackground } from '../types';
import { Icon } from '../components/Icon';

interface TemplateGalleryProps {
  onClose: () => void;
  worldCenter: () => { x: number; y: number };
}

interface TemplateDef {
  id: string;
  title: string;
  tagline: string;
  category: string;
  background: CanvasBackground;
  getObjects: (cx: number, cy: number) => CanvasObject[];
}

export const TEMPLATES: TemplateDef[] = [
  {
    id: 'study-notes',
    title: 'Study Notes',
    tagline: 'Structured learning with key concepts and summary sticky',
    category: 'Academic',
    background: 'grid',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 260,
        y: cy - 220,
        width: 520,
        height: 50,
        rotation: 0,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '🌿 Chapter 04: Principles & Foundations',
          fontFamily: "'Fraunces', serif",
          fontSize: 26,
          color: '#29272A',
          bold: true,
          italic: false,
          align: 'left',
          letterSpacing: 2,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx - 260,
        y: cy - 165,
        width: 520,
        height: 4,
        rotation: 0,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'divider',
          fill: '#A9BEA9',
          strokeColor: '#A9BEA9',
          strokeWidth: 2,
          opacity: 0.8,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx - 260,
        y: cy - 130,
        width: 240,
        height: 180,
        rotation: -1,
        zIndex: 2,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '💡 Core Concept:\nEvery complex system is built from simple, repeatable building blocks.',
          color: '#F8EFC9',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx + 10,
        y: cy - 130,
        width: 250,
        height: 180,
        rotation: 1.5,
        zIndex: 3,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '📌 Action Items:\n• Review definitions\n• Complete practice set\n• Draft revision flashcards',
          color: '#DCE7DC',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx - 260,
        y: cy + 70,
        width: 520,
        height: 100,
        rotation: 0,
        zIndex: 4,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'rounded-rect',
          fill: '#FFFDFB',
          strokeColor: '#E4DCF2',
          strokeWidth: 1.5,
          opacity: 0.95,
          rounded: 14,
          shadow: true,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 240,
        y: cy + 85,
        width: 480,
        height: 70,
        rotation: 0,
        zIndex: 5,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '✨ Summary: Focus on active recall and interconnected concepts. Write formulas in your own words.',
          fontFamily: "'DM Sans', sans-serif",
          fontSize: 16,
          color: '#4A4046',
          bold: false,
          italic: false,
          align: 'left',
          lineHeight: 1.5,
        },
      },
    ],
  },
  {
    id: 'revision-sheet',
    title: 'Revision Sheet',
    tagline: 'High-yield exam review grid with formulas and highlights',
    category: 'Academic',
    background: 'lined',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 280,
        y: cy - 200,
        width: 560,
        height: 44,
        rotation: 0,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '⚡ QUICK REVISION CHEAT SHEET',
          fontFamily: "'Fraunces', serif",
          fontSize: 22,
          color: '#7A3546',
          bold: true,
          italic: false,
          align: 'center',
          letterSpacing: 4,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx - 280,
        y: cy - 130,
        width: 260,
        height: 160,
        rotation: -2,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '🔑 Key Terms:\n• Term 1: Fundamental rule\n• Term 2: Special condition\n• Term 3: Exception case',
          color: '#FFF0F3',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx + 10,
        y: cy - 130,
        width: 270,
        height: 160,
        rotation: 1,
        zIndex: 2,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '📐 Must-Remember Equations:\n• F = m × a\n• E = mc²\n• Δx = v₀t + ½at²',
          color: '#E1EDF4',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'sticker',
        x: cx + 240,
        y: cy - 170,
        width: 50,
        height: 50,
        rotation: 12,
        zIndex: 3,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: { symbol: '★' },
      },
    ],
  },
  {
    id: 'moodboard',
    title: 'Aesthetic Moodboard',
    tagline: 'Collage layout with photo placeholders, swatches, and tape',
    category: 'Creative',
    background: 'paper',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 220,
        y: cy - 210,
        width: 440,
        height: 48,
        rotation: -2,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: 'autumn in the studio ☕',
          fontFamily: "'Caveat', cursive",
          fontSize: 34,
          color: '#4A4046',
          bold: true,
          italic: false,
          align: 'center',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx - 250,
        y: cy - 140,
        width: 170,
        height: 190,
        rotation: -4,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'rounded-rect',
          fill: '#F1D6DE',
          strokeColor: '#D78C9F',
          strokeWidth: 2,
          opacity: 0.85,
          rounded: 16,
          shadow: true,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx - 60,
        y: cy - 150,
        width: 180,
        height: 200,
        rotation: 3,
        zIndex: 2,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'rounded-rect',
          fill: '#EEDFC8',
          strokeColor: '#D8C7B5',
          strokeWidth: 2,
          opacity: 0.9,
          rounded: 16,
          shadow: true,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx + 140,
        y: cy - 130,
        width: 150,
        height: 180,
        rotation: -2,
        zIndex: 3,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'rounded-rect',
          fill: '#DCE7DC',
          strokeColor: '#A9BEA9',
          strokeWidth: 2,
          opacity: 0.9,
          rounded: 16,
          shadow: true,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'sticker',
        x: cx - 180,
        y: cy + 70,
        width: 48,
        height: 48,
        rotation: -8,
        zIndex: 4,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: { symbol: '✿' },
      },
      {
        id: crypto.randomUUID(),
        type: 'sticker',
        x: cx + 180,
        y: cy + 65,
        width: 48,
        height: 48,
        rotation: 10,
        zIndex: 5,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: { symbol: '✦' },
      },
    ],
  },
  {
    id: 'journal',
    title: 'Daily Journal',
    tagline: 'Gentle morning/evening reflections and gratitude prompts',
    category: 'Lifestyle',
    background: 'paper',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 220,
        y: cy - 200,
        width: 440,
        height: 44,
        rotation: 0,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '✦ Daily Reflections & Intentions',
          fontFamily: "'Fraunces', serif",
          fontSize: 24,
          color: '#29272A',
          bold: true,
          italic: false,
          align: 'center',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx - 250,
        y: cy - 130,
        width: 230,
        height: 180,
        rotation: -2,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '🌸 Morning Gratitude:\n1. Warm coffee\n2. Quiet morning sunlight\n3. Fresh clean start',
          color: '#FFF0F3',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx + 10,
        y: cy - 130,
        width: 240,
        height: 180,
        rotation: 2,
        zIndex: 2,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '🌙 Evening Wins:\n• Finished key priority\n• Went on a relaxing walk\n• Read 20 pages',
          color: '#E4DCF2',
        },
      },
    ],
  },
  {
    id: 'vision-board',
    title: 'Vision Board',
    tagline: 'Dream bigger: goals, affirmations, and inspirational vibes',
    category: 'Creative',
    background: 'pink',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 260,
        y: cy - 210,
        width: 520,
        height: 48,
        rotation: 0,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '✨ MY VISION & ASPIRATIONS ✨',
          fontFamily: "'Fraunces', serif",
          fontSize: 22,
          color: '#7A3546',
          bold: true,
          italic: false,
          align: 'center',
          letterSpacing: 4,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx - 240,
        y: cy - 140,
        width: 220,
        height: 150,
        rotation: -3,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '🚀 Career & Growth:\nShip projects with care and creative excellence.',
          color: '#F8EFC9',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx + 20,
        y: cy - 140,
        width: 220,
        height: 150,
        rotation: 3,
        zIndex: 2,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '🌿 Health & Calm:\nPrioritize restful sleep, nourishing food & movement.',
          color: '#DCE7DC',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx - 180,
        y: cy + 30,
        width: 360,
        height: 80,
        rotation: 0,
        zIndex: 3,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'rounded-rect',
          fill: '#FFFDFB',
          strokeColor: '#D78C9F',
          strokeWidth: 2,
          opacity: 0.95,
          rounded: 12,
          shadow: true,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 160,
        y: cy + 45,
        width: 320,
        height: 50,
        rotation: 0,
        zIndex: 4,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '“As you wish, so it shall become.” ♡',
          fontFamily: "'Caveat', cursive",
          fontSize: 24,
          color: '#B5657A',
          bold: true,
          italic: false,
          align: 'center',
        },
      },
    ],
  },
  {
    id: 'scrapbook',
    title: 'Scrapbook Memory',
    tagline: 'Playful scrapbook collage with tape, speech bubbles & stamps',
    category: 'Creative',
    background: 'paper',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx - 220,
        y: cy - 170,
        width: 200,
        height: 160,
        rotation: -5,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'rounded-rect',
          fill: '#FFF0F3',
          strokeColor: '#D78C9F',
          strokeWidth: 2,
          opacity: 0.9,
          rounded: 8,
          shadow: true,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx + 20,
        y: cy - 160,
        width: 210,
        height: 160,
        rotation: 4,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'speech-bubble',
          fill: '#F8EFC9',
          strokeColor: '#D4BA5B',
          strokeWidth: 2,
          opacity: 0.95,
          rounded: 12,
          shadow: true,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx + 40,
        y: cy - 135,
        width: 170,
        height: 80,
        rotation: 4,
        zIndex: 2,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: 'Best weekend ever! 🌸',
          fontFamily: "'Caveat', cursive",
          fontSize: 22,
          color: '#4A4046',
          bold: true,
          italic: false,
          align: 'center',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'sticker',
        x: cx - 180,
        y: cy + 20,
        width: 44,
        height: 44,
        rotation: 15,
        zIndex: 3,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: { symbol: '♡' },
      },
      {
        id: crypto.randomUUID(),
        type: 'sticker',
        x: cx + 150,
        y: cy + 30,
        width: 44,
        height: 44,
        rotation: -10,
        zIndex: 4,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: { symbol: '☁' },
      },
    ],
  },
  {
    id: 'photo-collage',
    title: 'Photo Collage',
    tagline: 'Polaroid gallery frames arranged for picture collections',
    category: 'Creative',
    background: 'paper',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx - 250,
        y: cy - 160,
        width: 220,
        height: 240,
        rotation: -4,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'rounded-rect',
          fill: '#FFFDFB',
          strokeColor: '#E2DAD1',
          strokeWidth: 2,
          opacity: 0.95,
          rounded: 6,
          shadow: true,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 240,
        y: cy + 35,
        width: 200,
        height: 35,
        rotation: -4,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: 'a little memory ✦',
          fontFamily: "'Caveat', cursive",
          fontSize: 18,
          color: '#756D72',
          bold: false,
          italic: false,
          align: 'center',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'shape',
        x: cx + 20,
        y: cy - 150,
        width: 220,
        height: 240,
        rotation: 3,
        zIndex: 2,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          shapeType: 'rounded-rect',
          fill: '#FFFDFB',
          strokeColor: '#E2DAD1',
          strokeWidth: 2,
          opacity: 0.95,
          rounded: 6,
          shadow: true,
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx + 30,
        y: cy + 45,
        width: 200,
        height: 35,
        rotation: 3,
        zIndex: 3,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: 'summer moments ☀️',
          fontFamily: "'Caveat', cursive",
          fontSize: 18,
          color: '#756D72',
          bold: false,
          italic: false,
          align: 'center',
        },
      },
    ],
  },
  {
    id: 'travel-board',
    title: 'Travel Itinerary',
    tagline: 'Trip planning: destinations, spots to eat, packing list',
    category: 'Lifestyle',
    background: 'sky',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 250,
        y: cy - 200,
        width: 500,
        height: 44,
        rotation: 0,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '✈️ Kyoto Trip Itinerary & Spots',
          fontFamily: "'Fraunces', serif",
          fontSize: 24,
          color: '#426E8E',
          bold: true,
          italic: false,
          align: 'center',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx - 260,
        y: cy - 130,
        width: 240,
        height: 170,
        rotation: -2,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '⛩️ Day 1 Itinerary:\n• Fushimi Inari Shrine\n• Matcha in Gion\n• Sunset at Kiyomizu-dera',
          color: '#E1EDF4',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx + 10,
        y: cy - 130,
        width: 250,
        height: 170,
        rotation: 2,
        zIndex: 2,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '🍜 Food & Cafes:\n• Ramen Sen no Kaze\n• Arabica Kyoto Arashiyama\n• Nishiki Market street food',
          color: '#F8EFC9',
        },
      },
    ],
  },
  {
    id: 'project-board',
    title: 'Project Kanban Board',
    tagline: 'Sprint columns: To Do, In Progress, and Completed Tasks',
    category: 'Productivity',
    background: 'blank',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 280,
        y: cy - 200,
        width: 560,
        height: 40,
        rotation: 0,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '🎯 Sprint 01 Roadmap & Deliverables',
          fontFamily: "'Fraunces', serif",
          fontSize: 22,
          color: '#29272A',
          bold: true,
          italic: false,
          align: 'center',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx - 280,
        y: cy - 130,
        width: 170,
        height: 180,
        rotation: 0,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '📋 TO DO\n• User research\n• Wireframe UI\n• Setup repo',
          color: '#F5EFE8',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx - 85,
        y: cy - 130,
        width: 170,
        height: 180,
        rotation: 0,
        zIndex: 2,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '⚙️ IN PROGRESS\n• Canvas gestures\n• Font Studio\n• Shape tool',
          color: '#F8EFC9',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'note',
        x: cx + 110,
        y: cy - 130,
        width: 170,
        height: 180,
        rotation: 0,
        zIndex: 3,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: '✅ DONE\n• Database v2\n• Top bar\n• Fast gestures',
          color: '#DCE7DC',
        },
      },
    ],
  },
  {
    id: 'blank-canvas',
    title: 'Clean Minimal Canvas',
    tagline: 'Simple centered title and greeting to begin fresh',
    category: 'Minimal',
    background: 'paper',
    getObjects: (cx, cy) => [
      {
        id: crypto.randomUUID(),
        type: 'text',
        x: cx - 180,
        y: cy - 50,
        width: 360,
        height: 60,
        rotation: 0,
        zIndex: 0,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: {
          text: 'A Little Thought…',
          fontFamily: "'Fraunces', serif",
          fontSize: 28,
          color: '#29272A',
          bold: true,
          italic: false,
          align: 'center',
        },
      },
      {
        id: crypto.randomUUID(),
        type: 'sticker',
        x: cx - 20,
        y: cy + 30,
        width: 40,
        height: 40,
        rotation: 0,
        zIndex: 1,
        locked: false,
        hidden: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        data: { symbol: '✦' },
      },
    ],
  },
];

export function TemplateGallery({ onClose, worldCenter }: TemplateGalleryProps) {
  const addObject = useCanvasStore((s) => s.addObject);
  const setBackground = useCanvasStore((s) => s.setBackground);

  const handleApplyTemplate = (tmpl: TemplateDef) => {
    const c = worldCenter();
    setBackground(tmpl.background);
    const objects = tmpl.getObjects(c.x, c.y);
    objects.forEach((obj) => addObject(obj));
    onClose();
  };

  return (
    <div className="template-gallery-modal" role="dialog" aria-label="Choose a Template">
      <div className="template-gallery-header">
        <div className="template-gallery-title">
          <Icon name="template" size={18} />
          <span>Starter Templates (10)</span>
        </div>
        <button className="icon-btn-sm" onClick={onClose} aria-label="Close">
          <Icon name="x" size={15} />
        </button>
      </div>

      <p className="template-gallery-subtitle">
        Every template creates real, fully-editable canvas objects — notes, text, shapes, and frames.
      </p>

      <div className="template-cards-grid">
        {TEMPLATES.map((t) => (
          <div
            key={t.id}
            className="template-card"
            onClick={() => handleApplyTemplate(t)}
          >
            <div className={`template-card-preview bg-${t.background}`}>
              <span className="template-badge">{t.category}</span>
              <div className="template-preview-mockup">
                <span className="mockup-bar" />
                <div className="mockup-notes">
                  <span className="mockup-note note-1" />
                  <span className="mockup-note note-2" />
                </div>
              </div>
            </div>
            <div className="template-card-info">
              <h3 className="template-card-title">{t.title}</h3>
              <p className="template-card-tagline">{t.tagline}</p>
              <button className="template-use-btn">
                <span>Insert on Canvas</span>
                <Icon name="arrow-right" size={13} />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
